export interface WordTraining {
  word: string;
  translation: string;
  example: string;
}

export const bodyParts: WordTraining[] = [
  { word: "head", translation: "cabeça", example: "I have a headache." },
  { word: "arm", translation: "braço", example: "She broke her arm." },
  { word: "leg", translation: "perna", example: "His leg is very strong." },
  { word: "hand", translation: "mão", example: "He raised his hand." },
  { word: "foot", translation: "pé", example: "My foot hurts." },
  { word: "eye", translation: "olho", example: "She has blue eyes." },
  { word: "ear", translation: "orelha", example: "Can you hear with your ear?" },
  { word: "nose", translation: "nariz", example: "My nose is cold." },
  { word: "mouth", translation: "boca", example: "Open your mouth, please." },
  { word: "shoulder", translation: "ombro", example: "He tapped my shoulder." },
  { word: "elbow", translation: "cotovelo", example: "She leaned on her elbow." },
  { word: "knee", translation: "joelho", example: "He injured his knee." },
  { word: "neck", translation: "pescoço", example: "I have a sore neck." },
  { word: "back", translation: "costas", example: "My back is hurting." },
  { word: "chest", translation: "peito", example: "He held his chest in pain." },
  { word: "stomach", translation: "estômago", example: "Her stomach is growling." },
  { word: "wrist", translation: "pulso", example: "She wears a bracelet on her wrist." },
  { word: "fingers", translation: "dedos (da mão)", example: "My fingers are cold." },
  { word: "toes", translation: "dedos do pé", example: "Wiggle your toes!" },
  { word: "tongue", translation: "língua", example: "Stick out your tongue." }
];

export const bodyParts2: WordTraining[] = [
  { word: "ankle", translation: "tornozelo", example: "He twisted his ankle." },
  { word: "heel", translation: "calcanhar", example: "Her heel hurts after walking." },
  { word: "thigh", translation: "coxa", example: "He has strong thighs." },
  { word: "calf", translation: "panturrilha", example: "My calf is sore from running." },
  { word: "hip", translation: "quadril", example: "She moved her hips to the music." },
  { word: "forehead", translation: "testa", example: "He has a scar on his forehead." },
  { word: "chin", translation: "queixo", example: "He scratched his chin." },
  { word: "cheek", translation: "bochecha", example: "She kissed his cheek." },
  { word: "eyebrow", translation: "sobrancelha", example: "Raise your eyebrow." },
  { word: "eyelash", translation: "cílio", example: "She has long eyelashes." },
  { word: "nail", translation: "unha", example: "He bit his nail nervously." },
  { word: "jaw", translation: "mandíbula", example: "Her jaw is sore from chewing." },
  { word: "rib", translation: "costela", example: "He broke a rib while playing." },
  { word: "waist", translation: "cintura", example: "Tie the belt around your waist." },
  { word: "spine", translation: "coluna vertebral", example: "She injured her spine." },
  { word: "palm", translation: "palma da mão", example: "He held the coin in his palm." },
  { word: "temple", translation: "têmpora", example: "She felt pain in her temple." },
  { word: "lips", translation: "lábios", example: "Her lips are chapped." },
  { word: "nostril", translation: "narina", example: "Smoke came out of his nostrils." },
  { word: "skull", translation: "crânio", example: "The helmet protects the skull." }
];

export const verbsList1: WordTraining[] = [
  { word: "run", translation: "correr", example: "I run every morning." },
  { word: "eat", translation: "comer", example: "They eat lunch together." },
  { word: "sleep", translation: "dormir", example: "He sleeps early." },
  { word: "read", translation: "ler", example: "She reads a book every night." },
  { word: "write", translation: "escrever", example: "I write in my journal daily." },
  { word: "walk", translation: "andar", example: "We walk in the park." },
  { word: "drink", translation: "beber", example: "He drinks water after running." },
  { word: "listen", translation: "ouvir", example: "Listen to the music." },
  { word: "speak", translation: "falar", example: "She speaks four languages." },
  { word: "jump", translation: "pular", example: "The kids jump on the trampoline." },
  { word: "watch", translation: "assistir", example: "We watch TV every evening." },
  { word: "play", translation: "jogar/brincar", example: "They play soccer on weekends." },
  { word: "cook", translation: "cozinhar", example: "I cook dinner for my family." },
  { word: "study", translation: "estudar", example: "She studies every afternoon." },
  { word: "open", translation: "abrir", example: "Open the door, please." },
  { word: "close", translation: "fechar", example: "Close the window." },
  { word: "drive", translation: "dirigir", example: "He drives to work." },
  { word: "learn", translation: "aprender", example: "We learn new words every day." },
  { word: "teach", translation: "ensinar", example: "She teaches English." },
  { word: "clean", translation: "limpar", example: "I clean my room every weekend." }
];

export const verbsList2: WordTraining[] = [
  { word: "draw", translation: "desenhar", example: "He draws animals." },
  { word: "paint", translation: "pintar", example: "She paints with oils." },
  { word: "sing", translation: "cantar", example: "They sing beautifully." },
  { word: "dance", translation: "dançar", example: "Let's dance together." },
  { word: "buy", translation: "comprar", example: "I buy fruit at the market." },
  { word: "sell", translation: "vender", example: "He sells clothes." },
  { word: "wait", translation: "esperar", example: "Please wait here." },
  { word: "call", translation: "ligar", example: "She calls her mom every day." },
  { word: "help", translation: "ajudar", example: "They help each other." },
  { word: "hug", translation: "abraçar", example: "He hugs his dog." },
  { word: "kiss", translation: "beijar", example: "She kisses her baby." },
  { word: "laugh", translation: "rir", example: "We laugh at the jokes." },
  { word: "cry", translation: "chorar", example: "The baby cries a lot." },
  { word: "fix", translation: "consertar", example: "He fixes the bike." },
  { word: "build", translation: "construir", example: "They build houses." },
  { word: "break", translation: "quebrar", example: "Don't break the glass." },
  { word: "send", translation: "enviar", example: "I send emails daily." },
  { word: "receive", translation: "receber", example: "She receives a gift." },
  { word: "choose", translation: "escolher", example: "Choose your favorite color." },
  { word: "find", translation: "encontrar", example: "He finds his keys quickly." }
];

export const verbsList3: WordTraining[] = [
  { word: "lose", translation: "perder", example: "I lose my phone often." },
  { word: "win", translation: "vencer", example: "They win every match." },
  { word: "travel", translation: "viajar", example: "We love to travel." },
  { word: "arrive", translation: "chegar", example: "She arrives at 9 a.m." },
  { word: "leave", translation: "sair/partir", example: "They leave early in the morning." },
  { word: "stay", translation: "ficar", example: "Stay here, please." },
  { word: "sit", translation: "sentar", example: "Please sit down." },
  { word: "stand", translation: "ficar de pé", example: "He stands in line." },
  { word: "grow", translation: "crescer", example: "The plant grows fast." },
  { word: "cut", translation: "cortar", example: "She cuts the paper." },
  { word: "throw", translation: "jogar/lançar", example: "He throws the ball." },
  { word: "catch", translation: "pegar", example: "Catch the ball!" },
  { word: "dig", translation: "cavar", example: "They dig a hole." },
  { word: "climb", translation: "escalar", example: "She climbs mountains." },
  { word: "push", translation: "empurrar", example: "Push the door." },
  { word: "pull", translation: "puxar", example: "Pull the handle." },
  { word: "bake", translation: "assar", example: "I bake cakes every weekend." },
  { word: "wash", translation: "lavar", example: "He washes the car." },
  { word: "iron", translation: "passar (roupa)", example: "She irons the clothes." },
  { word: "brush", translation: "escovar", example: "I brush my teeth." }
];

export const verbsList4: WordTraining[] = [
  { word: "shout", translation: "gritar", example: "He shouts loudly." },
  { word: "whisper", translation: "sussurrar", example: "They whisper secrets." },
  { word: "smile", translation: "sorrir", example: "She smiles a lot." },
  { word: "frown", translation: "franzir a testa", example: "He frowns when he's confused." },
  { word: "ride", translation: "andar (de bicicleta/cavalo)", example: "I ride my bike to school." },
  { word: "surf", translation: "surfar", example: "They surf every summer." },
  { word: "ski", translation: "esquiar", example: "He skis in the Alps." },
  { word: "skate", translation: "andar de skate", example: "She skates in the park." },
  { word: "sweep", translation: "varrer", example: "I sweep the floor every day." },
  { word: "mop", translation: "passar pano", example: "She mops the kitchen floor." },
  { word: "plant", translation: "plantar", example: "We plant flowers in spring." },
  { word: "harvest", translation: "colher", example: "They harvest apples in the fall." },
  { word: "repair", translation: "reparar", example: "He repairs electronics." },
  { word: "decorate", translation: "decorar", example: "She decorates the room." },
  { word: "invite", translation: "convidar", example: "I invite friends to my party." },
  { word: "answer", translation: "responder", example: "Please answer the question." },
  { word: "ask", translation: "perguntar", example: "Ask the teacher for help." },
  { word: "borrow", translation: "pegar emprestado", example: "Can I borrow your pen?" },
  { word: "lend", translation: "emprestar", example: "She lends me her book." },
  { word: "promise", translation: "prometer", example: "I promise to be careful." }
];

export const objectsList1: WordTraining[] = [
  { word: "table", translation: "mesa", example: "The table is made of wood." },
  { word: "chair", translation: "cadeira", example: "She sat on the chair." },
  { word: "pen", translation: "caneta", example: "I lost my pen." },
  { word: "pencil", translation: "lápis", example: "Sharpen your pencil." },
  { word: "book", translation: "livro", example: "He is reading a book." },
  { word: "notebook", translation: "caderno", example: "I wrote it in my notebook." },
  { word: "backpack", translation: "mochila", example: "His backpack is heavy." },
  { word: "lamp", translation: "lâmpada/abajur", example: "Turn off the lamp." },
  { word: "mirror", translation: "espelho", example: "She looked in the mirror." },
  { word: "window", translation: "janela", example: "Open the window, please." },
  { word: "door", translation: "porta", example: "The door is locked." },
  { word: "clock", translation: "relógio de parede", example: "The clock is ticking." },
  { word: "bottle", translation: "garrafa", example: "He filled the bottle with water." },
  { word: "phone", translation: "telefone", example: "My phone is charging." },
  { word: "computer", translation: "computador", example: "The computer is new." },
  { word: "keyboard", translation: "teclado", example: "The keyboard is wireless." },
  { word: "mouse", translation: "mouse", example: "Click with the mouse." },
  { word: "television", translation: "televisão", example: "The television is on." },
  { word: "remote", translation: "controle remoto", example: "Where's the remote?" },
  { word: "sofa", translation: "sofá", example: "He sat on the sofa." }
];

export const objectsList2: WordTraining[] = [
  { word: "bed", translation: "cama", example: "The bed is comfortable." },
  { word: "blanket", translation: "cobertor", example: "I need a blanket." },
  { word: "pillow", translation: "travesseiro", example: "She hugged her pillow." },
  { word: "cup", translation: "xícara", example: "He drank from the cup." },
  { word: "plate", translation: "prato", example: "Put the food on the plate." },
  { word: "fork", translation: "garfo", example: "Use a fork to eat pasta." },
  { word: "spoon", translation: "colher", example: "She stirred with a spoon." },
  { word: "knife", translation: "faca", example: "Be careful with the knife." },
  { word: "fridge", translation: "geladeira", example: "The milk is in the fridge." },
  { word: "stove", translation: "fogão", example: "The stove is hot." },
  { word: "microwave", translation: "micro-ondas", example: "Heat it in the microwave." },
  { word: "toaster", translation: "torradeira", example: "The toaster is broken." },
  { word: "blender", translation: "liquidificador", example: "Use the blender for smoothies." },
  { word: "pan", translation: "frigideira", example: "Put oil in the pan." },
  { word: "pot", translation: "panela", example: "The pot is boiling." },
  { word: "bowl", translation: "tigela", example: "Pour soup in the bowl." },
  { word: "shelf", translation: "prateleira", example: "Books are on the shelf." },
  { word: "fan", translation: "ventilador", example: "Turn on the fan." },
  { word: "rug", translation: "tapete", example: "The rug is soft." },
  { word: "curtain", translation: "cortina", example: "Close the curtain, please." }
];

export const objectsList3: WordTraining[] = [
  { word: "wallet", translation: "carteira", example: "He lost his wallet." },
  { word: "watch", translation: "relógio de pulso", example: "My watch is waterproof." },
  { word: "glasses", translation: "óculos", example: "I can't see without my glasses." },
  { word: "hat", translation: "chapéu", example: "She wears a red hat." },
  { word: "shoes", translation: "sapatos", example: "Your shoes are dirty." },
  { word: "socks", translation: "meias", example: "I need clean socks." },
  { word: "belt", translation: "cinto", example: "His belt is too tight." },
  { word: "jacket", translation: "jaqueta", example: "It’s cold, wear a jacket." },
  { word: "umbrella", translation: "guarda-chuva", example: "Take your umbrella." },
  { word: "bag", translation: "bolsa/sacola", example: "She carries a bag." },
  { word: "ring", translation: "anel", example: "He wears a gold ring." },
  { word: "necklace", translation: "colar", example: "The necklace is beautiful." },
  { word: "bracelet", translation: "pulseira", example: "Her bracelet is silver." },
  { word: "suitcase", translation: "mala", example: "Pack your suitcase." },
  { word: "helmet", translation: "capacete", example: "Wear a helmet when biking." },
  { word: "mask", translation: "máscara", example: "Use a mask in the hospital." },
  { word: "gloves", translation: "luvas", example: "These gloves are warm." },
  { word: "scarf", translation: "cachecol", example: "He bought a red scarf." },
  { word: "coat", translation: "casaco", example: "It’s snowing, get your coat." },
  { word: "boots", translation: "botas", example: "She wears boots in the rain." }
];

export const objectsList4: WordTraining[] = [
  { word: "camera", translation: "câmera", example: "He took a photo with the camera." },
  { word: "tripod", translation: "tripé", example: "The camera is on the tripod." },
  { word: "microphone", translation: "microfone", example: "She speaks into the microphone." },
  { word: "speaker", translation: "caixa de som", example: "The speaker is loud." },
  { word: "headphones", translation: "fones de ouvido", example: "I use headphones at work." },
  { word: "charger", translation: "carregador", example: "I forgot my phone charger." },
  { word: "tablet", translation: "tablet", example: "The tablet is very light." },
  { word: "printer", translation: "impressora", example: "Print it with the printer." },
  { word: "scanner", translation: "scanner", example: "Use the scanner for the document." },
  { word: "folder", translation: "pasta", example: "Put the papers in the folder." },
  { word: "envelope", translation: "envelope", example: "Seal the envelope carefully." },
  { word: "calendar", translation: "calendário", example: "Check the date on the calendar." },
  { word: "bin", translation: "lixeira", example: "Throw it in the bin." },
  { word: "tape", translation: "fita adesiva", example: "He used tape to fix it." },
  { word: "glue", translation: "cola", example: "Use glue for the project." },
  { word: "eraser", translation: "borracha", example: "I need an eraser." },
  { word: "ruler", translation: "régua", example: "Draw a line with the ruler." },
  { word: "scissors", translation: "tesoura", example: "Cut the paper with scissors." },
  { word: "stapler", translation: "grampeador", example: "Staple the pages together." },
  { word: "paperclip", translation: "clipe de papel", example: "Add a paperclip to hold it." }
];

export const objectsList5: WordTraining[] = [
  { word: "bucket", translation: "balde", example: "Fill the bucket with water." },
  { word: "broom", translation: "vassoura", example: "Use the broom to clean." },
  { word: "dustpan", translation: "pá de lixo", example: "Get the dustpan for the crumbs." },
  { word: "mop", translation: "mop (esfregão)", example: "She cleaned with a mop." },
  { word: "vacuum", translation: "aspirador", example: "Use the vacuum on the carpet." },
  { word: "soap", translation: "sabão", example: "Wash your hands with soap." },
  { word: "sponge", translation: "esponja", example: "Clean the dishes with a sponge." },
  { word: "towel", translation: "toalha", example: "Dry with a towel." },
  { word: "hanger", translation: "cabide", example: "Hang your shirt on a hanger." },
  { word: "basket", translation: "cesto", example: "Put the clothes in the basket." },
  { word: "iron", translation: "ferro de passar", example: "I need to iron my shirt." },
  { word: "laundry", translation: "roupa suja", example: "The laundry is piling up." },
  { word: "soap dispenser", translation: "dispensador de sabão", example: "Refill the soap dispenser." },
  { word: "trash can", translation: "lixeira", example: "Take out the trash can." },
  { word: "plunger", translation: "desentupidor", example: "Use the plunger in the bathroom." },
  { word: "mirror cabinet", translation: "armário com espelho", example: "The mirror cabinet is in the bathroom." },
  { word: "toilet paper", translation: "papel higiênico", example: "Replace the toilet paper." },
  { word: "shampoo", translation: "shampoo", example: "I need more shampoo." },
  { word: "conditioner", translation: "condicionador", example: "Apply the conditioner after shampoo." },
  { word: "razor", translation: "lâmina de barbear", example: "Be careful with the razor." }
];

export const objectsList6: WordTraining[] = [
  { word: "hammer", translation: "martelo", example: "He hit the nail with a hammer." },
  { word: "nail", translation: "prego", example: "The nail is too short." },
  { word: "screwdriver", translation: "chave de fenda", example: "Use a screwdriver to fix it." },
  { word: "screw", translation: "parafuso", example: "Tighten the screw." },
  { word: "wrench", translation: "chave inglesa", example: "Pass me the wrench." },
  { word: "pliers", translation: "alicate", example: "Cut the wire with pliers." },
  { word: "tape measure", translation: "trena", example: "Measure it with a tape measure." },
  { word: "toolbox", translation: "caixa de ferramentas", example: "He opened the toolbox." },
  { word: "drill", translation: "furadeira", example: "Use the drill carefully." },
  { word: "ladder", translation: "escada", example: "Climb the ladder safely." },
  { word: "saw", translation: "serrote", example: "Cut the wood with a saw." },
  { word: "paintbrush", translation: "pincel", example: "Dip the paintbrush in paint." },
  { word: "roller", translation: "rolo de pintura", example: "Use a roller for the wall." },
  { word: "bucket of paint", translation: "balde de tinta", example: "He opened the bucket of paint." },
  { word: "tool belt", translation: "cinto de ferramentas", example: "He wears a tool belt." },
  { word: "chisel", translation: "formão", example: "Carve it with a chisel." },
  { word: "level", translation: "nível", example: "Check if it's straight with a level." },
  { word: "flashlight", translation: "lanterna", example: "Use the flashlight in the dark." },
  { word: "extension cord", translation: "extensão elétrica", example: "Plug it into the extension cord." },
  { word: "safety goggles", translation: "óculos de proteção", example: "Wear safety goggles while cutting." }
];

export const objectsList7: WordTraining[] = [
  { word: "car", translation: "carro", example: "The car is parked outside." },
  { word: "motorcycle", translation: "moto", example: "He rides a motorcycle." },
  { word: "bicycle", translation: "bicicleta", example: "She uses a bicycle to go to school." },
  { word: "cap", translation: "boné", example: "He wears a cap on sunny days." },
  { word: "seatbelt", translation: "cinto de segurança", example: "Fasten your seatbelt." },
  { word: "trunk", translation: "porta-malas", example: "Open the trunk of the car." },
  { word: "tire", translation: "pneu", example: "The tire is flat." },
  { word: "steering wheel", translation: "volante", example: "Turn the steering wheel slowly." },
  { word: "windshield", translation: "para-brisa", example: "Clean the windshield." },
  { word: "gear", translation: "marcha", example: "Shift the gear smoothly." },
  { word: "brake", translation: "freio", example: "Press the brake gently." },
  { word: "accelerator", translation: "acelerador", example: "Push the accelerator carefully." },
  { word: "dashboard", translation: "painel", example: "Look at the dashboard lights." },
  { word: "frame", translation: "porta-retrato", example: "Put the photo in a frame." },
  { word: "headlight", translation: "farol", example: "Turn on the headlights." },
  { word: "horn", translation: "buzina", example: "Press the horn if needed." },
  { word: "license plate", translation: "placa", example: "Check the license plate number." },
  { word: "glove compartment", translation: "porta-luvas", example: "Put it in the glove compartment." },
  { word: "jack", translation: "macaco", example: "Use the jack to lift the car." },
  { word: "fuel tank", translation: "tanque de combustível", example: "Fill the fuel tank." }
];

export const objectsList8: WordTraining[] = [
  { word: "candle", translation: "vela", example: "Light the candle." },
  { word: "lighter", translation: "isqueiro", example: "Use a lighter to start the fire." },
  { word: "match", translation: "fósforo", example: "Strike a match carefully." },
  { word: "fire extinguisher", translation: "extintor de incêndio", example: "Grab the fire extinguisher!" },
  { word: "first aid kit", translation: "kit de primeiros socorros", example: "Where is the first aid kit?" },
  { word: "thermometer", translation: "termômetro", example: "Check your temperature with a thermometer." },
  { word: "medicine", translation: "remédio", example: "Take your medicine." },
  { word: "bandage", translation: "curativo", example: "Apply a bandage on the cut." },
  { word: "pills", translation: "comprimidos", example: "She takes her pills daily." },
  { word: "syringe", translation: "seringa", example: "The nurse prepared a syringe." },
  { word: "stethoscope", translation: "estetoscópio", example: "The doctor uses a stethoscope." },
  { word: "wheelchair", translation: "cadeira de rodas", example: "He uses a wheelchair." },
  { word: "crutches", translation: "muletas", example: "She walks with crutches." },
  { word: "oxygen mask", translation: "máscara de oxigênio", example: "Put on the oxygen mask." },
  { word: "scalpel", translation: "bisturi", example: "The scalpel is sharp." },
  { word: "clipboard", translation: "prancheta", example: "Write it on the clipboard." },
  { word: "gurney", translation: "maca", example: "Move the patient on the gurney." },
  { word: "IV bag", translation: "bolsa de soro", example: "Hang the IV bag." },
  { word: "disinfectant", translation: "desinfetante", example: "Use disinfectant to clean." },
  { word: "bandage roll", translation: "rolo de bandagem", example: "Wrap the bandage roll around the injury." }
];

export const foodsList1: WordTraining[] = [
  { word: "bread", translation: "pão", example: "I eat bread every morning." },
  { word: "cheese", translation: "queijo", example: "She loves cheese on toast." },
  { word: "butter", translation: "manteiga", example: "Spread butter on the bread." },
  { word: "egg", translation: "ovo", example: "He boils an egg for breakfast." },
  { word: "milk", translation: "leite", example: "I drink milk at night." },
  { word: "yogurt", translation: "iogurte", example: "Yogurt is good for digestion." },
  { word: "apple", translation: "maçã", example: "She eats an apple every day." },
  { word: "banana", translation: "banana", example: "Bananas are rich in potassium." },
  { word: "orange", translation: "laranja", example: "Orange juice is refreshing." },
  { word: "grape", translation: "uva", example: "Grapes can be green or purple." },
  { word: "pear", translation: "pêra", example: "He sliced the pear." },
  { word: "peach", translation: "pêssego", example: "Peaches are sweet and soft." },
  { word: "strawberry", translation: "morango", example: "She made strawberry jam." },
  { word: "pineapple", translation: "abacaxi", example: "Pineapple is very juicy." },
  { word: "watermelon", translation: "melancia", example: "Watermelon is perfect for summer." },
  { word: "melon", translation: "melão", example: "Melon has a soft flavor." },
  { word: "mango", translation: "manga", example: "Mango is my favorite fruit." },
  { word: "papaya", translation: "mamão", example: "Papaya helps digestion." },
  { word: "lemon", translation: "limão", example: "Add lemon to the tea." },
  { word: "avocado", translation: "abacate", example: "Avocados are full of nutrients." }
];

export const foodsList2: WordTraining[] = [
  { word: "rice", translation: "arroz", example: "Rice is a staple food." },
  { word: "beans", translation: "feijão", example: "He eats rice and beans every day." },
  { word: "pasta", translation: "macarrão", example: "She cooked pasta for lunch." },
  { word: "spaghetti", translation: "espaguete", example: "I love spaghetti with tomato sauce." },
  { word: "pizza", translation: "pizza", example: "We ordered a large pizza." },
  { word: "hamburger", translation: "hambúrguer", example: "The hamburger is delicious." },
  { word: "hot dog", translation: "cachorro-quente", example: "Kids love hot dogs." },
  { word: "chicken", translation: "frango", example: "He roasted a chicken." },
  { word: "beef", translation: "carne bovina", example: "Beef is expensive." },
  { word: "pork", translation: "carne de porco", example: "She made pork chops." },
  { word: "fish", translation: "peixe", example: "Fish is rich in omega-3." },
  { word: "shrimp", translation: "camarão", example: "They served shrimp with garlic." },
  { word: "eggplant", translation: "berinjela", example: "Eggplant is often fried." },
  { word: "carrot", translation: "cenoura", example: "Rabbits love carrots." },
  { word: "potato", translation: "batata", example: "He made mashed potatoes." },
  { word: "lettuce", translation: "alface", example: "She added lettuce to the salad." },
  { word: "tomato", translation: "tomate", example: "Tomatoes are used in sauces." },
  { word: "onion", translation: "cebola", example: "Onions add flavor to food." },
  { word: "garlic", translation: "alho", example: "He chopped garlic for the dish." },
  { word: "corn", translation: "milho", example: "They grilled corn at the party." }
];

export const foodsList3: WordTraining[] = [
  { word: "cabbage", translation: "repolho", example: "Cabbage can be eaten raw." },
  { word: "broccoli", translation: "brócolis", example: "Broccoli is very healthy." },
  { word: "cauliflower", translation: "couve-flor", example: "She steamed cauliflower." },
  { word: "spinach", translation: "espinafre", example: "Spinach is full of iron." },
  { word: "pumpkin", translation: "abóbora", example: "Pumpkin pie is popular in fall." },
  { word: "zucchini", translation: "abobrinha", example: "Zucchini is great in salads." },
  { word: "peas", translation: "ervilhas", example: "Peas are small and green." },
  { word: "cucumber", translation: "pepino", example: "Add cucumber to the salad." },
  { word: "beet", translation: "beterraba", example: "Beet juice is very red." },
  { word: "radish", translation: "rabanete", example: "Radish has a spicy taste." },
  { word: "chili", translation: "pimenta", example: "Chili peppers are hot!" },
  { word: "olive", translation: "azeitona", example: "I like black olives." },
  { word: "mushroom", translation: "cogumelo", example: "Mushrooms grow in forests." },
  { word: "cheeseburger", translation: "x-burguer", example: "He ate a big cheeseburger." },
  { word: "fried chicken", translation: "frango frito", example: "Fried chicken is crispy." },
  { word: "omelet", translation: "omelete", example: "She made a cheese omelet." },
  { word: "toast", translation: "torrada", example: "He had toast with jam." },
  { word: "cereal", translation: "cereal", example: "I eat cereal with milk." },
  { word: "jam", translation: "geleia", example: "Jam is made from fruit." },
  { word: "honey", translation: "mel", example: "Honey is sweet and sticky." }
];

export const foodsList4: WordTraining[] = [
  { word: "cake", translation: "bolo", example: "The birthday cake was delicious." },
  { word: "pie", translation: "torta", example: "Apple pie is a classic dessert." },
  { word: "cookie", translation: "biscoito", example: "He baked chocolate chip cookies." },
  { word: "chocolate", translation: "chocolate", example: "She loves dark chocolate." },
  { word: "ice cream", translation: "sorvete", example: "Let's eat ice cream!" },
  { word: "pudding", translation: "pudim", example: "Vanilla pudding is my favorite." },
  { word: "candy", translation: "doce/bala", example: "Kids eat too much candy." },
  { word: "popcorn", translation: "pipoca", example: "We had popcorn at the movie." },
  { word: "nuts", translation: "nozes", example: "Nuts are a healthy snack." },
  { word: "almond", translation: "amêndoa", example: "Almonds are crunchy." },
  { word: "cashew", translation: "castanha de caju", example: "Cashews are used in cooking." },
  { word: "peanut", translation: "amendoim", example: "He is allergic to peanuts." },
  { word: "granola", translation: "granola", example: "She eats granola with yogurt." },
  { word: "juice", translation: "suco", example: "He drank orange juice." },
  { word: "soda", translation: "refrigerante", example: "Soda is very sugary." },
  { word: "coffee", translation: "café", example: "I drink black coffee." },
  { word: "tea", translation: "chá", example: "She drinks green tea." },
  { word: "smoothie", translation: "vitamina/batida", example: "Make a banana smoothie." },
  { word: "milkshake", translation: "milkshake", example: "He ordered a chocolate milkshake." },
  { word: "water", translation: "água", example: "Drink water every day." }
];
